'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import SQLGeminiChatBot from "../../components/cahtbot/index";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Siva electronics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const hideLayout = pathname === "/login"; // Hide Navbar & ChatBot on the login page

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {!hideLayout && <Navbar />}
        {!hideLayout && <SQLGeminiChatBot />}
        {children}
      </body>
    </html>
  );
}
