'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import SQLGeminiChatBot from "../../components/cahtbot/index";
import { usePathname } from "next/navigation";
import {AlertProvider} from "../app/context/alert/index"
import Alert from "../app/alert/index"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Siva electronics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const hideLayout = pathname === ("/login" || "/signup"); // Hide Navbar & ChatBot on the login page

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AlertProvider>
        {!hideLayout && <Navbar />}
        {!hideLayout && <SQLGeminiChatBot />}
        {children}
         <Alert />
        </AlertProvider>
      </body>

    </html>
  );
}
